### ISSUE TITLE
Web Page Title Not Changed From Vite+React

### ISSUE THREAD

**Issue by JoelJaison394** [devishraq/quotes-generator-react#2]
I noticed that the title of your web page is displaying as "vite+react" instead of a custom title or the expected title.

**Comment by devishraq** [comment]
Site title has been changed to 'Quotes Generator App' and issue closed....

<img width="680" alt="image" src="https://github.com/devishraq/quotes-generator-react/assets/101325013/37d367a3-1b07-4f2f-980e-17e497535dde">
